### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/MPV-appimage#10]
i have three  videos 
![image](https://github.com/ivan-hc/MPV-appimage/assets/87791643/9fbe64e3-af6b-4529-a6e4-ceb56aa03563)

this is can open 
![image](https://github.com/ivan-hc/MPV-appimage/assets/87791643/fa824f98-f8e7-420b-94bb-0bdc5ad057b7)

but two and three cannot
![image](https://github.com/ivan-hc/MPV-appimage/assets/87791643/c80a6907-b0aa-49cf-ae17-2ff18c253669)

**Comment by ivan-hc** [comment]
Yes, I'm working on it right now, thank you

**Comment by ivan-hc** [comment]
I can't provide the latest version for now.

Please, download a fallback from https://github.com/ivan-hc/MPV-appimage/releases/tag/stable-releases

I'll try to fix the issue soon.

**Comment by ivan-hc** [comment]
by changing the AppRun from

echo "$APP $@" | $HERE/.local/share/junest/bin/junest proot -n -b "--bind=/home --bind=/home/$(echo $USER) --bind=/media --bind=/opt"
to

    $HERE/.local/share/junest/bin/junest proot -n -b "--bind=/home --bind=/home/$(echo $USER) --bind=/media --bind=/opt" -- $APP "$@"

"$@" means that the option can read files with "spaces" in the name.

At least this has meen solved.

Before I close this issue, I want to resolve the issue with YouTube and other streams.

**Comment by ivan-hc** [comment]
Your issue is solved, you can play videos locally.

However, videos on YouTube or other streaming platforms can't be played. For that kind of media use the [stable-releases](https://github.com/ivan-hc/MPV-appimage/releases/tag/stable-releases) instead... if streaming is not something you use, you're ok with the one from [here](https://github.com/ivan-hc/MPV-appimage/releases/tag/continuous)
