### ISSUE TITLE
Missing libs

### ISSUE THREAD

**Issue by thenoobtester** [ivan-hc/MPV-appimage#2]
Hi,

I tried to run the Appimage on Debian 9 and it seems to be missing a bunch of libs ( libavutil57, libavcodec59, libavformat59, libswscale6, etc.) which is funny because they are listed in your build script however when I extract the Appimage they are not inside. I found libavcodec58 and libavformat58 in the Appimage for example.

Thank you for this try by the way.

**Comment by ivan-hc** [comment]
hi, can you provide the correct package name (for bionic) that contains all the missing libraries?

**Comment by thenoobtester** [comment]
Well I think the packages are the ones (and their dependencies) listed in the build script, that is:

  packages:
    - libavutil57
    - libavcodec59
    - libavformat59
    - libswscale6
    - libavfilter8
    - libswresample4
    - libva2

**Comment by ivan-hc** [comment]
right now I've re-built this on my PC using the list of dependences available at https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/mpv_0.27.2-1ubuntu1_amd64.deb.html for MPV 0.27, this is the recipe:

app: mpv
binpatch: true
ingredients:
  dist: bionic
  sources:
    - deb http://archive.ubuntu.com/ubuntu/ bionic main universe restricted multiverse
    - deb http://archive.ubuntu.com/ubuntu bionic-security main universe restricted multiverse
    - deb http://archive.ubuntu.com/ubuntu/ bionic-updates main universe restricted multiverse
  ppas:
    - savoury1/ffmpeg4
    - savoury1/mpv
    - savoury1/build-tools
    - savoury1/backports
    - savoury1/graphics
    - savoury1/multimedia
  packages:
    - mpv
    - ffmpeg
    - libasound2
    - libass9
    - libavcodec-extra57
    - libavcodec57
    - libavdevice57
    - libavfilter-extra6
    - libavfilter6
    - libavformat57
    - libavutil55
    - libbluray2
    - libcaca0
    - libcdio-cdda2
    - libcdio-paranoia2
    - libcdio17
    - libdrm2
    - libdvdnav4
    - libdvdread4
    - libegl1
    - libgbm1
    - libgl1
    - libjack-0.125
    - libjack-jackd2-0
    - libjpeg8
    - liblcms2-2
    - liblua5.2-0
    - libpulse0
    - librubberband2
    - libsdl2-2.0-0
    - libsmbclient
    - libsndio6.1
    - libswresample2
    - libswscale4
    - libuchardet0
    - libva-drm2
    - libva-wayland2
    - libva-x11-2
    - libva2
    - libvdpau1
    - libwayland-client0
    - libwayland-cursor0
    - libwayland-egl1
    - libwayland-egl1-mesa
    - libx11-6
    - libxext6
    - libxinerama1
    - libxkbcommon0
    - libxrandr2
    - libxss1
    - libxv1
    - zlib1g

The final AppImage takes 150 MB of disk space

**Comment by thenoobtester** [comment]
Ok, thank you for the recipe.

**Comment by ivan-hc** [comment]
I've just seen if the savoury1's PPAs from where this appimage is built has libavcodec59 and it is available in savoury1/ffmpeg5, but it seems unusable with the MPV's PPA due to some incompatibilities between Ubuntu 18.04 and newer libraries (on the other hand, savoury1 is making a miracle with its project), for more details visit https://bugs.launchpad.net/savos/+bug/1965181

I have to do some tests on two VMs before I can made the changes in this repository.

Anyway, is this AppImage working normally on your system right now?

UPDATE: just tested on Debian and Arch, everything works like a charm, now wait at least 20 minutes from this message to have the new release at https://github.com/ivan-hc/MPV-appimage/releases/tag/continuous

**Comment by thenoobtester** [comment]
"Anyway, is this AppImage working normally on your system right now?"

I finally didn't build it because the feature i was interested in is only available starting with mpv 0.34.

As far as the lastest appimage is concerned it has the same issue as the first one for some reasons it's not packing the necessary libs. I tried to run it and again got 'libavutil.so.57: cannot open shared object file: No such file or directory'. Your build script doesn't seem to pack all the necessary libs. But never mind, the feature I needed is just being able to see the chapter names on a mouse hover, so don't worry about this.
When you say 'just tested on Debian', which version was it and did you just download your Appimage and ran it on it?

PS:if you do 'ldd mpv' then your Appimage should pack all the libs listed I think.

**Comment by ivan-hc** [comment]
> When you say 'just tested on Debian', which version was it and did you just download your Appimage and ran it on it?

Debian Testing (host), Debian Unstable and Arch Linux (guests in Virtualbox), I don't need to test them on older distributions because I already know that all depend on the `libc6` version, newer programs cannot run on older systems, while old programs will always run on any new release, and this is the reason why I've abandoned the development of [Arch-Deployer](https://github.com/ivan-hc/Arch-Deployer), it may be useful only for Arch Linux users and systems with a `GLIBC` version equal or bigger than the one available on Arch.

About the missing libraries, I already know that pkg2appimage is unable to bundle some libraries, that's why a part of my AppImage packages have an AppRun that exports `LD_LIBRARY_PATH` from the host too, for example:

https://github.com/ivan-hc/MPV-appimage/blob/3d3e8a844e9b93e68045d10f4c31a429c419ddba/mpv#L106

the AppImage uses libraries from both the bundle and the host, this is the only way I have to run VLC with the H264 support, for example. The only tests I do with MPV are playing some videos, but I'm not a fan of MPV, nor I have to use something different from VLC normally. I create an AppImage that works the 70-80% standalone, so they are not perfect, I'm not a real developer too, I do this in my little spare time, when I don't work (while I'm writing thi message I'm at home, I have an hour, then I have to go work again via train, when you sent the reply I was working, I work into a Supermarket). So consider these repositories just a start for something bigger, I can only provide a base, but if you want you can join the repo and provide your improvements the way you think it is better. These AppImages will be updated to the last version always, or at least until the PPA's owner will still provide these packages.

**Comment by ivan-hc** [comment]
Try this new release, is based on JuNest (Arch Linux-based distro that works as guest on any distro) and includes all libraries it needs: https://github.com/ivan-hc/MPV-appimage/releases/tag/continuous
