### ISSUE TITLE
Included libs are messy

### ISSUE THREAD

**Issue by fulalas** [ivan-hc/MPV-appimage#3]
This project is a really nice iniciative! Congratulations :)

It would be nice to clean up the included libs. There are 2 FFMpeg versions, and both are wrong:
![Screenshot_2022-12-12_20-20-34](https://user-images.githubusercontent.com/27843666/206984529-71798f53-278a-415b-aa07-9bce6f624974.png)

Suggestion: test it on a live minimalist distro like Porteus so you'll be sure it will run in basically any system :)

**Comment by ivan-hc** [comment]
hi and sorry for the long waiting, [pkg2appimage](https://github.com/AppImageCommunity/pkg2appimage) is the tool used to build this AppImage by downloading the deb package with all its dependences from a repository/PPA (in this case Ubuntu 18.04 "Bionic"). This tool also has the difect of create AppImage packages too bloated sometime, and in the case of MPV, `libavcodec.so.58` must be included by default due to the packages available on the PPA for that old Ubuntu version, also if this AppImage does not use it. The other version (ie the one vith the number "57") is built inside this AppImage after some tests on a Fedora-based system (see the first two issues before the yours, [here](https://github.com/ivan-hc/MPV-appimage/issues?q=is%3Aissue+is%3Aclosed)). In the end i decided to rely on the ffmpeg version available on the host, however the libraries "58" must be there because they are necessary to build the structure, also if they are useless.

I've abandoned this repository for a while, and you're right, the AppImage is too muchbloated because there are some residuates of my old tests. Right now I've re-edited the main script by including only "mpv" among the necessary packages in the recipe.yml file. The new release is now available:

https://github.com/ivan-hc/MPV-appimage/releases/tag/continuous

now the package is about 50 MB smaller. Just tested on Debian and Arch and it works fine for me.

PS: sorry for the long waiting and thanks for this feedback.

Now I can close this issue, but if you need to re-open it with furter improvements, feel free to re-open it or open another issue.

Have a nice day :)

**Comment by fulalas** [comment]
@ivan-hc, thanks for your kind and detailed reply. I understand and agree with everything you say. I've just tested your new version but on Porteus (Slackware 15.0 x64 based) it doesn't work:

```
/tmp/.mount_MPV-MeGWSqmq/usr/bin/mpv: /lib64/libncursesw.so.5: no version information available (required by /tmp/.mount_MPV-MeGWSqmq/usr/lib/x86_64-linux-gnu/libcaca.so.0)
/tmp/.mount_MPV-MeGWSqmq/usr/bin/mpv: /lib64/libncursesw.so.5: no version information available (required by /tmp/.mount_MPV-MeGWSqmq/usr/lib/x86_64-linux-gnu/libcaca.so.0)
/tmp/.mount_MPV-MeGWSqmq/usr/bin/mpv: symbol lookup error: /usr/lib64/libpango-1.0.so.0: undefined symbol: g_memdup2
```

I believe (and I might be wrong) the best way to build an AppImage is to use a minimalist distro so you can guarantee it will work in any distro. Live session using a VM would be easy, I guess :)

**Comment by ivan-hc** [comment]
I have some difficults in build some AppImages without having to rely on some libraries on the host that must be in place. This (and other projects on my repository) are only things I do for fun, and if someone is interested in improve them, I'm here. It would be great if someone helps me in made better AppImage packages. For now I can rely more on some tests I can do on my machines, but I have not much feedback like this, nor the support of the AppImage community or the main developers of each project. Pratically no one cares about AppImages an a great part of the developers have to work on Flatpak because they have to build their apps on a good and stable environment (runtimes) and I like the work around the Flatpak's ecosystem. What I don't like about it is the amount of sizes of each runtime (and the apps are uncompressed too, see 0ad, as a Flatpak it takes the double of the sizes of the AppImage version). The more the developers rely on Flatpak, the more the AppImage package format is dead. Sad but true. I can't do much alone, and this is my best.

**Comment by ivan-hc** [comment]
Hi, try this new release, is based on JuNest (Arch Linux-based distro that works as guest on any distro) and includes all libraries it needs: https://github.com/ivan-hc/MPV-appimage/releases/tag/continuous

**Comment by fulalas** [comment]
This one works! Thanks a lot! :)

A few tips:

1. you could build mpv after building/installing `nv-codec-headers` to add support to hardware acceleration on Nvidia cards
2. you could build with Lua support so mpv can provide a better OSD experience, inclusing 'i' key to give information about the current video
3. you could include `/etc/mpv/input.conf` with the following:
```
Alt+RIGHT add video-rotate 90
Alt+LEFT add video-rotate -90
UP add volume 2
DOWN add volume -2
ALT+ENTER cycle fullscreen
MOUSE_BTN3 add volume 2
MOUSE_BTN4 add volume -2
MOUSE_BTN0 cycle pause
```
5. when I execute your mpv I see this in the terminal: `/etc/profile: line 6: cat: No such file or directory`
6. also lots of warnings and errors (that I don't see using my build):
```
[vo/gpu/x11] XOpenIM() failed. Unicode input will not work.
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu/opengl] No primary DRM device could be picked!
[vo/gpu/opengl] Failed to find a usable DRM primary node!
[vo/gpu/opengl] Failed to create KMS.
[vo/gpu-next/x11] XOpenIM() failed. Unicode input will not work.
[vo/gpu-next] Can't handle VT release - signal already used
[vo/gpu-next/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu-next/opengl] No primary DRM device could be picked!
[vo/gpu-next/opengl] Failed to find a usable DRM primary node!
[vo/gpu-next/opengl] Failed to create KMS.
[vo/vdpau/x11] XOpenIM() failed. Unicode input will not work.
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
[vo/vdpau] Error when calling vdp_device_create_x11: 1
[vo/xv/x11] XOpenIM() failed. Unicode input will not work.
[vo/xv] Warning: this legacy VO has bad quality and performance, and will in particular result in blurry OSD and subtitles. You should fix your graphics drivers, or not force the xv VO.
```

**Comment by ivan-hc** [comment]
Interesting... why not you fork this repo with these improvements? 

To edit [mpv-junest.sh](https://github.com/ivan-hc/MPV-appimage/blob/main/mpv-junest.sh) is quite easy, all guidelines will tell you how this script works.

> 5. when I execute your mpv I see this in the terminal: `/etc/profile: line 6: cat: No such file or directory`

this is because this AppImage needs to see /etc to work with online streams, maybe it see two /etc/profile files (just rebuilt on my PC, the error was on line 4 instead, `/etc/profile: line 4: id: No such file or directory`)

> 6. also lots of warnings and errors (that I don't see using my build)

This is because mpv expects to find drivers of "Arch Linux", normally installed in /usr/libs/dri... and I've removed that directory (due to the size), so mpv is looking for local drivers as a fallback. This is the disadvantage of non-native software. JuNest is hosted at https://github.com/fsquillace/junest

So this is a bug report, it would be best to open a new issue, or better a PR seen all this stuff. It would be great if someone else helps me improving this, so I can work on other stuff! I've lost a full day yesterday trying to find a solution for online streaming issues.
