### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/MPV-appimage#7]
![image](https://github.com/ivan-hc/MPV-appimage/assets/87791643/d90c628f-37c0-49bb-b126-9423a3a3127a)

**Comment by ivan-hc** [comment]
A lot of errors are related to the fact that I've removed /usr/lib/dr from the AppImage, it contains drivers and the size of the AppImage can ammount to 200 MB or more. I'll study a solution, but any suggestion is wellcome.

**Comment by ivan-hc** [comment]
I can't reproduce your error, I get different ones than yours, but this is surely due to the different video cards, also this AppImage runs in an "emulated" environment with its own drivers. 

MPV seems to redirect to host drivers not finding the ones it would expect on the guest (JuNest). 

From suggestions around the forums it seems to be a common error, even though the drivers and various modules are present. Perhaps JuNest does not act directly on the hardware and creates a bridge between the guest system and the host. So it shouldn't be a problem as long as the videos work.

PS: I also tried reinstalling various packages with pacman inside the extracted Appimage:

    ./*AppImage ---appimage-extract
    HOME=/path/to/squashfs-root/
    ./squashfs-root/.local/share/junest/bin/junest -- sudo pacman -Syy
    ./squashfs-root/.local/share/junest/bin/junest -- sudo pacman -Syu
    ./squashfs-root/.local/share/junest/bin/junest -- sudo pacman -S libx11 vdpauinfo mesa-vdpau libvdpau_nvidia libva-vdpau-driver

the errors are still the same. 

However, as long as MPV works, there's no need to worry.
